// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/handler-launcher-com/notify/v1/notify.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	pkg/handler-launcher-com/notify/v1/notify.proto

It has these top-level messages:
	DomainEventRequest
	K8SEventRequest
	Response
	LifecycleMetricRequest
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DomainEventRequest struct {
	DomainJSON []byte `protobuf:"bytes,1,opt,name=domainJSON,proto3" json:"domainJSON,omitempty"`
	StatusJSON []byte `protobuf:"bytes,2,opt,name=statusJSON,proto3" json:"statusJSON,omitempty"`
	EventType  string `protobuf:"bytes,3,opt,name=eventType" json:"eventType,omitempty"`
}

func (m *DomainEventRequest) Reset()                    { *m = DomainEventRequest{} }
func (m *DomainEventRequest) String() string            { return proto.CompactTextString(m) }
func (*DomainEventRequest) ProtoMessage()               {}
func (*DomainEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DomainEventRequest) GetDomainJSON() []byte {
	if m != nil {
		return m.DomainJSON
	}
	return nil
}

func (m *DomainEventRequest) GetStatusJSON() []byte {
	if m != nil {
		return m.StatusJSON
	}
	return nil
}

func (m *DomainEventRequest) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

type K8SEventRequest struct {
	EventJSON []byte `protobuf:"bytes,1,opt,name=eventJSON,proto3" json:"eventJSON,omitempty"`
}

func (m *K8SEventRequest) Reset()                    { *m = K8SEventRequest{} }
func (m *K8SEventRequest) String() string            { return proto.CompactTextString(m) }
func (*K8SEventRequest) ProtoMessage()               {}
func (*K8SEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *K8SEventRequest) GetEventJSON() []byte {
	if m != nil {
		return m.EventJSON
	}
	return nil
}

type Response struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LifecycleMetricRequest struct {
	MetricJSON []byte `protobuf:"bytes,1,opt,name=metricJSON,proto3" json:"metricJSON,omitempty"`
}

func (m *LifecycleMetricRequest) Reset()                    { *m = LifecycleMetricRequest{} }
func (m *LifecycleMetricRequest) String() string            { return proto.CompactTextString(m) }
func (*LifecycleMetricRequest) ProtoMessage()               {}
func (*LifecycleMetricRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LifecycleMetricRequest) GetMetricJSON() []byte {
	if m != nil {
		return m.MetricJSON
	}
	return nil
}

func init() {
	proto.RegisterType((*DomainEventRequest)(nil), "kubevirt.notify.v1.DomainEventRequest")
	proto.RegisterType((*K8SEventRequest)(nil), "kubevirt.notify.v1.K8sEventRequest")
	proto.RegisterType((*Response)(nil), "kubevirt.notify.v1.Response")
	proto.RegisterType((*LifecycleMetricRequest)(nil), "kubevirt.notify.v1.LifecycleMetricRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Notify service

type NotifyClient interface {
	HandleDomainEvent(ctx context.Context, in *DomainEventRequest, opts ...grpc.CallOption) (*Response, error)
	HandleLifecycleMetricEvent(ctx context.Context, in *LifecycleMetricRequest, opts ...grpc.CallOption) (*Response, error)
	HandleK8SEvent(ctx context.Context, in *K8SEventRequest, opts ...grpc.CallOption) (*Response, error)
}

type notifyClient struct {
	cc *grpc.ClientConn
}

func NewNotifyClient(cc *grpc.ClientConn) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) HandleDomainEvent(ctx context.Context, in *DomainEventRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.notify.v1.Notify/HandleDomainEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) HandleLifecycleMetricEvent(ctx context.Context, in *LifecycleMetricRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.notify.v1.Notify/HandleLifecycleMetricEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) HandleK8SEvent(ctx context.Context, in *K8SEventRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.notify.v1.Notify/HandleK8sEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notify service

type NotifyServer interface {
	HandleDomainEvent(context.Context, *DomainEventRequest) (*Response, error)
	HandleLifecycleMetricEvent(context.Context, *LifecycleMetricRequest) (*Response, error)
	HandleK8SEvent(context.Context, *K8SEventRequest) (*Response, error)
}

func RegisterNotifyServer(s *grpc.Server, srv NotifyServer) {
	s.RegisterService(&_Notify_serviceDesc, srv)
}

func _Notify_HandleDomainEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).HandleDomainEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.notify.v1.Notify/HandleDomainEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).HandleDomainEvent(ctx, req.(*DomainEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_HandleLifecycleMetricEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LifecycleMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).HandleLifecycleMetricEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.notify.v1.Notify/HandleLifecycleMetricEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).HandleLifecycleMetricEvent(ctx, req.(*LifecycleMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_HandleK8SEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).HandleK8SEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.notify.v1.Notify/HandleK8SEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).HandleK8SEvent(ctx, req.(*K8SEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubevirt.notify.v1.Notify",
	HandlerType: (*NotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleDomainEvent",
			Handler:    _Notify_HandleDomainEvent_Handler,
		},
		{
			MethodName: "HandleLifecycleMetricEvent",
			Handler:    _Notify_HandleLifecycleMetricEvent_Handler,
		},
		{
			MethodName: "HandleK8sEvent",
			Handler:    _Notify_HandleK8SEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/handler-launcher-com/notify/v1/notify.proto",
}

func init() { proto.RegisterFile("pkg/handler-launcher-com/notify/v1/notify.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x6d, 0x95, 0xda, 0x0e, 0xa2, 0xb8, 0x07, 0x29, 0xa5, 0x48, 0x89, 0x20, 0x45, 0x68,
	0x42, 0xf5, 0xd2, 0x93, 0x07, 0x51, 0x10, 0xff, 0x54, 0x58, 0xf5, 0xa2, 0xa7, 0x74, 0x3b, 0x6d,
	0x42, 0x93, 0xdd, 0xb8, 0xbb, 0x09, 0xe4, 0x0b, 0xf9, 0x39, 0x25, 0x9b, 0x86, 0xc4, 0x36, 0xd0,
	0x5b, 0xf6, 0x37, 0x3b, 0xf3, 0xf6, 0xbd, 0x09, 0x38, 0xd1, 0x6a, 0xe9, 0x78, 0x2e, 0x9f, 0x07,
	0x28, 0x47, 0x81, 0x1b, 0x73, 0xe6, 0xa1, 0x1c, 0x31, 0x11, 0x3a, 0x5c, 0x68, 0x7f, 0x91, 0x3a,
	0xc9, 0x78, 0xfd, 0x65, 0x47, 0x52, 0x68, 0x41, 0xc8, 0x2a, 0x9e, 0x61, 0xe2, 0x4b, 0x6d, 0xaf,
	0x71, 0x32, 0xb6, 0x24, 0x90, 0x7b, 0x11, 0xba, 0x3e, 0x7f, 0x48, 0x90, 0x6b, 0x8a, 0x3f, 0x31,
	0x2a, 0x4d, 0xce, 0x01, 0xe6, 0x86, 0x3e, 0xbd, 0xbf, 0x4d, 0xbb, 0x8d, 0x41, 0x63, 0x78, 0x44,
	0x2b, 0x24, 0xab, 0x2b, 0xed, 0xea, 0x58, 0x99, 0x7a, 0x33, 0xaf, 0x97, 0x84, 0xf4, 0xa1, 0x83,
	0xd9, 0xbc, 0x8f, 0x34, 0xc2, 0xee, 0xfe, 0xa0, 0x31, 0xec, 0xd0, 0x12, 0x58, 0x0e, 0x9c, 0x3c,
	0x4f, 0xd4, 0x3f, 0xc1, 0xa2, 0xa1, 0xa2, 0x57, 0x02, 0xeb, 0x16, 0xda, 0x14, 0x55, 0x24, 0xb8,
	0x42, 0xd2, 0x85, 0x43, 0x15, 0x33, 0x86, 0x4a, 0x99, 0x7b, 0x6d, 0x5a, 0x1c, 0xb3, 0x4a, 0x88,
	0x4a, 0xb9, 0x4b, 0x34, 0x2f, 0xea, 0xd0, 0xe2, 0x68, 0x4d, 0xe0, 0xec, 0xc5, 0x5f, 0x20, 0x4b,
	0x59, 0x80, 0xaf, 0xa8, 0xa5, 0xcf, 0x2a, 0x46, 0x43, 0x03, 0xaa, 0x46, 0x4b, 0x72, 0xfd, 0xdb,
	0x84, 0xd6, 0xd4, 0x84, 0x45, 0xbe, 0xe1, 0xf4, 0xd1, 0x84, 0x5d, 0xc9, 0x8b, 0x5c, 0xda, 0xdb,
	0x99, 0xda, 0xdb, 0x81, 0xf6, 0xfa, 0x75, 0xf7, 0x0a, 0x4f, 0xd6, 0x1e, 0xf1, 0xa0, 0x97, 0x0f,
	0xdf, 0x78, 0x67, 0xae, 0x72, 0x55, 0xd7, 0x5d, 0xef, 0x68, 0xa7, 0xd2, 0x27, 0x1c, 0xe7, 0x4a,
	0xc5, 0x0a, 0xc8, 0x45, 0x5d, 0xc7, 0xc6, 0x82, 0x76, 0x8d, 0xbd, 0x3b, 0xf8, 0x6a, 0x26, 0xe3,
	0x59, 0xcb, 0xfc, 0x68, 0x37, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x47, 0x4c, 0xaf, 0x36, 0x9b,
	0x02, 0x00, 0x00,
}
